version: '3.8'

services:
  backend:
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_CLUSTER}/${MONGO_DATABASE}?retryWrites=true&w=majority
      SPRING_DATA_MONGODB_DATABASE: ${MONGO_DATABASE}
    # 'depends_on' should not be used unless your frontend must be up before backend starts.
    # Remove the line below if there is no such dependency.
#    depends_on:
#      - frontend

  frontend:
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80/index.html" ]
      interval: 30s
      timeout: 10s
      retries: 3
    build:
      context: ./movie-gold-v1
      dockerfile: Dockerfile
    ports:
      - "3000:80"
#    depends_on:
#      - backend
#
#volumes:
#  mongodb_data: